<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'created_at' => '2024-11-29 13:48:39',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-briefcase',
                'id' => 1,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.configuration',
                'type' => 3,
                'updated_at' => '2024-11-29 13:48:39',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            1 => 
            array (
                'created_at' => '2024-11-29 13:49:12',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-newspaper',
                'id' => 2,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.trd',
                'type' => 1,
                'updated_at' => '2024-11-29 13:49:12',
                'updated_by' => 0,
                'uri' => 'trd.index',
            ),
            2 => 
            array (
                'created_at' => '2024-12-03 09:18:01',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-person',
                'id' => 3,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.provider',
                'type' => 1,
                'updated_at' => '2024-12-03 09:18:01',
                'updated_by' => 0,
                'uri' => 'provider.index',
            ),
            3 => 
            array (
                'created_at' => '2024-12-04 16:04:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-newspaper',
                'id' => 4,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.document_management',
                'type' => 3,
                'updated_at' => '2024-12-04 16:04:20',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            4 => 
            array (
                'created_at' => '2024-12-05 08:22:27',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-chain',
                'id' => 5,
                'method' => NULL,
                'parent_id' => 4,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.dependencies',
                'type' => 1,
                'updated_at' => '2024-12-05 08:22:27',
                'updated_by' => 0,
                'uri' => 'dependencies.index',
            ),
            5 => 
            array (
                'created_at' => '2024-12-05 13:55:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-user-group',
                'id' => 6,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.users_group',
                'type' => 1,
                'updated_at' => '2024-12-05 13:55:42',
                'updated_by' => 0,
                'uri' => 'users-group.index',
            ),
            6 => 
            array (
                'created_at' => '2024-12-06 15:35:41',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-hourglass',
                'id' => 7,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.hours_work',
                'type' => 1,
                'updated_at' => '2024-12-10 09:15:24',
                'updated_by' => 0,
                'uri' => 'hours-work.index',
            ),
            7 => 
            array (
                'created_at' => '2024-12-10 10:12:22',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-hourglass-end',
                'id' => 8,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.hours_not_work',
                'type' => 1,
                'updated_at' => '2024-12-10 10:12:22',
                'updated_by' => 0,
                'uri' => 'hours-not-work.index',
            ),
            8 => 
            array (
                'created_at' => '2024-12-10 14:09:15',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-archive',
                'id' => 9,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.payroll_management',
                'type' => 1,
                'updated_at' => '2024-12-10 14:09:15',
                'updated_by' => 0,
                'uri' => 'payroll-management.index',
            ),
            9 => 
            array (
                'created_at' => '2024-12-12 14:39:53',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-brands fa-dropbox',
                'id' => 10,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.variables_templates',
                'type' => 1,
                'updated_at' => '2024-12-12 14:39:53',
                'updated_by' => 0,
                'uri' => 'variables-templates.index',
            ),
            10 => 
            array (
                'created_at' => '2024-12-17 08:29:04',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-regular fa-user',
                'id' => 11,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.user_interoperability',
                'type' => 1,
                'updated_at' => '2024-12-17 08:29:04',
                'updated_by' => 0,
                'uri' => 'user-interoperability.index',
            ),
            11 => 
            array (
                'created_at' => '2024-12-17 14:02:19',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-question',
                'id' => 12,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.satisfaction_survey',
                'type' => 1,
                'updated_at' => '2024-12-17 14:02:19',
                'updated_by' => 0,
                'uri' => 'satisfaction-survey.index',
            ),
            12 => 
            array (
                'created_at' => '2024-12-17 16:32:41',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-cubes',
                'id' => 13,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.regional',
                'type' => 1,
                'updated_at' => '2024-12-17 16:32:41',
                'updated_by' => 0,
                'uri' => 'regional.index',
            ),
            13 => 
            array (
                'created_at' => '2024-12-19 14:53:40',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-cloud-upload',
                'id' => 14,
                'method' => NULL,
                'parent_id' => 4,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.charge_trd',
                'type' => 1,
                'updated_at' => '2024-12-19 15:15:06',
                'updated_by' => 0,
                'uri' => 'charge.trd',
            ),
            14 => 
            array (
                'created_at' => '2025-01-09 13:17:05',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-columns',
                'id' => 15,
                'method' => NULL,
                'parent_id' => 4,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.trd_versioning',
                'type' => 1,
                'updated_at' => '2025-01-09 13:17:05',
                'updated_by' => 0,
                'uri' => 'trd-versioning.index',
            ),
            15 => 
            array (
                'created_at' => '2025-01-17 07:50:34',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file',
                'id' => 16,
                'method' => NULL,
                'parent_id' => 4,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.exp_files',
                'type' => 1,
                'updated_at' => '2025-01-17 07:50:34',
                'updated_by' => 0,
                'uri' => 'files-exp.index',
            ),
            16 => 
            array (
                'created_at' => '2025-01-27 09:56:38',
                'created_by' => 3,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-check',
                'id' => 33,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.types_of_filings',
                'type' => 1,
                'updated_at' => '2025-01-27 09:56:38',
                'updated_by' => 0,
                'uri' => 'types-filings.index',
            ),
            17 => 
            array (
                'created_at' => '2025-01-27 12:40:33',
                'created_by' => 3,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-gear',
                'id' => 34,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.filling_setting',
                'type' => 1,
                'updated_at' => '2025-01-27 12:40:33',
                'updated_by' => 0,
                'uri' => 'filling-setting.index',
            ),
            18 => 
            array (
                'created_at' => '2025-01-29 08:40:49',
                'created_by' => 3,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-tag',
                'id' => 35,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.radication_label',
                'type' => 1,
                'updated_at' => '2025-01-29 08:40:49',
                'updated_by' => 0,
                'uri' => 'radication-labels.index',
            ),
            19 => 
            array (
                'created_at' => '2025-01-31 15:43:44',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-archive',
                'id' => 36,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.archive_gestion',
                'type' => 3,
                'updated_at' => '2025-01-31 15:43:44',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            20 => 
            array (
                'created_at' => '2025-01-31 15:45:14',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-building',
                'id' => 37,
                'method' => NULL,
                'parent_id' => 36,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.physicalspace',
                'type' => 1,
                'updated_at' => '2025-01-31 15:45:14',
                'updated_by' => 0,
                'uri' => 'physicalspace.index',
            ),
            21 => 
            array (
                'created_at' => '2025-02-04 11:22:36',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-level-down',
                'id' => 38,
                'method' => NULL,
                'parent_id' => 36,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.archive_files',
                'type' => 1,
                'updated_at' => '2025-02-04 11:22:36',
                'updated_by' => 0,
                'uri' => 'files-exp.archive',
            ),
            22 => 
            array (
                'created_at' => '2025-02-08 09:57:41',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-reply-all',
                'id' => 39,
                'method' => NULL,
                'parent_id' => 36,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.transfer_docs',
                'type' => 1,
                'updated_at' => '2025-02-08 09:57:41',
                'updated_by' => 0,
                'uri' => 'files-exp.transfer',
            ),
            23 => 
            array (
                'created_at' => '2025-02-10 08:39:55',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file-pdf',
                'id' => 40,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'filing.filing',
                'type' => 1,
                'updated_at' => '2025-02-10 08:39:55',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            24 => 
            array (
                'created_at' => '2025-02-10 08:40:39',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file-text',
                'id' => 41,
                'method' => NULL,
                'parent_id' => 40,
                'status' => 1,
                'target' => '_self',
                'title' => 'filing.standard_filing',
                'type' => 1,
                'updated_at' => '2025-02-10 08:40:39',
                'updated_by' => 0,
                'uri' => 'filing.index',
            ),
            25 => 
            array (
                'created_at' => '2025-02-13 08:05:45',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-code-fork',
                'id' => 42,
                'method' => NULL,
                'parent_id' => 4,
                'status' => 1,
                'target' => '_self',
                'title' => 'document_management.table_control',
                'type' => 1,
                'updated_at' => '2025-02-13 08:05:45',
                'updated_by' => 0,
                'uri' => 'files-exp.tableControl',
            ),
            26 => 
            array (
                'created_at' => '2025-02-13 14:44:55',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-code-fork',
                'id' => 43,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'workflow',
                'type' => 1,
                'updated_at' => '2025-02-13 14:44:55',
                'updated_by' => 0,
                'uri' => 'workflow.index',
            ),
            27 => 
            array (
                'created_at' => '2025-02-24 07:56:54',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file-lines',
                'id' => 44,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'documentary_loans.documentary_loans',
                'type' => 3,
                'updated_at' => '2025-02-24 07:56:54',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            28 => 
            array (
                'created_at' => '2025-02-24 08:03:11',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-brands fa-cc-mastercard',
                'id' => 45,
                'method' => NULL,
                'parent_id' => 44,
                'status' => 1,
                'target' => '_self',
                'title' => 'documentary_loans.request_loans',
                'type' => 1,
                'updated_at' => '2025-02-24 08:03:11',
                'updated_by' => 0,
                'uri' => 'request-loans.index',
            ),
            29 => 
            array (
                'created_at' => '2025-02-24 11:35:44',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-regular fa-circle',
                'id' => 46,
                'method' => NULL,
                'parent_id' => 44,
                'status' => 1,
                'target' => '_self',
                'title' => 'documentary_loans.admin_loans',
                'type' => 1,
                'updated_at' => '2025-02-24 11:35:44',
                'updated_by' => 0,
                'uri' => 'admin-loans.adminLoans',
            ),
            30 => 
            array (
                'created_at' => '2025-02-25 13:57:19',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file',
                'id' => 47,
                'method' => NULL,
                'parent_id' => 44,
                'status' => 1,
                'target' => '_self',
                'title' => 'documentary_loans.loans_exp',
                'type' => 1,
                'updated_at' => '2025-02-25 13:57:19',
                'updated_by' => 0,
                'uri' => 'loans-exp.index',
            ),
            31 => 
            array (
                'created_at' => '2025-02-25 14:54:08',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-angle-double-right',
                'id' => 48,
                'method' => NULL,
                'parent_id' => 44,
                'status' => 1,
                'target' => '_self',
                'title' => 'documentary_loans.admin_loans_exp',
                'type' => 1,
                'updated_at' => '2025-02-25 14:54:08',
                'updated_by' => 0,
                'uri' => 'admin-loans-exp-exp.adminLoans',
            ),
            32 => 
            array (
                'created_at' => '2025-03-03 09:19:07',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-envelope',
                'id' => 49,
                'method' => NULL,
                'parent_id' => 40,
                'status' => 1,
                'target' => '_self',
                'title' => 'filing.email_filing',
                'type' => 1,
                'updated_at' => '2025-03-03 09:19:07',
                'updated_by' => 0,
                'uri' => 'email.index',
            ),
            33 => 
            array (
                'created_at' => '2025-03-03 09:19:38',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file-excel',
                'id' => 50,
                'method' => NULL,
                'parent_id' => 40,
                'status' => 1,
                'target' => '_self',
                'title' => 'filing.masive_filing',
                'type' => 1,
                'updated_at' => '2025-03-03 09:19:38',
                'updated_by' => 0,
                'uri' => 'filing.masiveFilingView',
            ),
            34 => 
            array (
                'created_at' => '2025-03-03 15:04:07',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-list',
                'id' => 51,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.report',
                'type' => 3,
                'updated_at' => '2025-03-03 15:04:07',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            35 => 
            array (
                'created_at' => '2025-03-03 15:11:51',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-list',
                'id' => 52,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.permissions',
                'type' => 1,
                'updated_at' => '2025-03-03 15:11:51',
                'updated_by' => 0,
                'uri' => 'permissions.reports',
            ),
            36 => 
            array (
                'created_at' => '2025-03-03 17:28:49',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-eye',
                'id' => 53,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.log',
                'type' => 1,
                'updated_at' => '2025-03-03 17:28:49',
                'updated_by' => 0,
                'uri' => 'logs.index',
            ),
            37 => 
            array (
                'created_at' => '2025-03-05 17:19:03',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-inbox',
                'id' => 54,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'correspondence_management.correspondence_management',
                'type' => 3,
                'updated_at' => '2025-03-05 17:19:03',
                'updated_by' => 0,
                'uri' => 'main',
            ),
            38 => 
            array (
                'created_at' => '2025-03-05 17:19:48',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-paper-plane',
                'id' => 55,
                'method' => NULL,
                'parent_id' => 54,
                'status' => 1,
                'target' => '_self',
                'title' => 'correspondence_management.distribution_and_shippings',
                'type' => 1,
                'updated_at' => '2025-03-05 17:19:48',
                'updated_by' => 0,
                'uri' => 'distributionshipping.index',
            ),
            39 => 
            array (
                'created_at' => '2025-03-06 08:08:08',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-exchange',
                'id' => 56,
                'method' => NULL,
                'parent_id' => 54,
                'status' => 1,
                'target' => '_self',
                'title' => 'correspondence_management.mass_reassignment',
                'type' => 1,
                'updated_at' => '2025-03-06 08:08:08',
                'updated_by' => 0,
                'uri' => 'mass-reasing.index',
            ),
            40 => 
            array (
                'created_at' => '2025-03-06 10:32:16',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-ban',
                'id' => 57,
                'method' => NULL,
                'parent_id' => 54,
                'status' => 1,
                'target' => '_self',
                'title' => 'correspondence_management.cancellation_request',
                'type' => 1,
                'updated_at' => '2025-03-06 10:32:16',
                'updated_by' => 0,
                'uri' => 'cancellation-request.index',
            ),
            41 => 
            array (
                'created_at' => '2025-03-11 09:00:58',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-align-left',
                'id' => 58,
                'method' => NULL,
                'parent_id' => 36,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.dispo_final',
                'type' => 1,
                'updated_at' => '2025-03-11 09:00:58',
                'updated_by' => 0,
                'uri' => 'dispo_final.index',
            ),
            42 => 
            array (
                'created_at' => '2025-03-11 11:32:19',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-list',
                'id' => 59,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.filing',
                'type' => 1,
                'updated_at' => '2025-03-11 11:32:19',
                'updated_by' => 0,
                'uri' => 'filing-days.reports',
            ),
            43 => 
            array (
                'created_at' => '2025-03-11 11:32:53',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-list',
                'id' => 60,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.filing_type',
                'type' => 1,
                'updated_at' => '2025-03-11 11:32:53',
                'updated_by' => 0,
                'uri' => 'filing-by-type.reports',
            ),
            44 => 
            array (
                'created_at' => '2025-03-11 11:33:12',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-align-left',
                'id' => 61,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.filing_person',
                'type' => 1,
                'updated_at' => '2025-03-11 11:33:12',
                'updated_by' => 0,
                'uri' => 'filing-person.reports',
            ),
            45 => 
            array (
                'created_at' => '2025-03-11 11:49:42',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-align-left',
                'id' => 62,
                'method' => NULL,
                'parent_id' => 51,
                'status' => 1,
                'target' => '_self',
                'title' => 'report.exp_file',
                'type' => 1,
                'updated_at' => '2025-03-11 11:49:42',
                'updated_by' => 0,
                'uri' => 'exp-file-class.reports',
            ),
            46 => 
            array (
                'created_at' => '2025-03-12 20:11:43',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-person',
                'id' => 63,
                'method' => NULL,
                'parent_id' => 1,
                'status' => 1,
                'target' => '_self',
                'title' => 'configuration.third',
                'type' => 1,
                'updated_at' => '2025-03-12 20:11:43',
                'updated_by' => 0,
                'uri' => 'third.index',
            ),
            47 => 
            array (
                'created_at' => '2025-03-13 17:24:58',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-archive',
                'id' => 65,
                'method' => NULL,
                'parent_id' => 36,
                'status' => 1,
                'target' => '_self',
                'title' => 'archive_gestion.accumulated_funds',
                'type' => 1,
                'updated_at' => '2025-03-13 17:24:58',
                'updated_by' => 0,
                'uri' => 'accumulated-fund.index',
            ),
            48 => 
            array (
                'created_at' => '2025-04-23 16:52:05',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => 0,
                'icon' => 'fa-solid fa-file',
                'id' => 66,
                'method' => NULL,
                'parent_id' => 0,
                'status' => 1,
                'target' => '_self',
                'title' => 'user_manual.user_manual',
                'type' => 1,
                'updated_at' => '2025-04-23 16:52:05',
                'updated_by' => 0,
                'uri' => 'manual-usuario.index',
            ),
        ));
        
        
    }
}