<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    use HasFactory;

    public function save(array $options = [])
    {
        if(!$this->created_by) {
            $this->created_by = auth()->user()?auth()->user()->id:1;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function update(array $attributes = [], array $options = [])
    {
        if(isset($attributes['status']) && $attributes['status'] == 0){
            $this->deleted_by = auth()->user()?auth()->user()->id:1;
            $this->deleted_at = date('Y-m-d H:i:s');
        }else{
            $this->deleted_by = 0;
            $this->updated_by = auth()->user()?auth()->user()->id:1;
        }
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function author(){
        return $this->belongsTo(User::class,'created_by');
    }

    public function editor(){
        return $this->belongsTo(User::class,'updated_by');
    }

}
